<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'sku' => 'TECH-001',
                'name' => 'Wireless Noise-Cancelling Headphones',
                'slug' => 'wireless-headphones',
                'description' => 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality.',
                'price' => 299.99,
                'original_price' => 399.99,
                'category_id' => 1,
                'brand_id' => 1,
                'rating' => 4.80,
                'reviews_count' => 234,
                'stock' => 45,
                'in_stock' => true,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'sku' => 'FASH-001',
                'name' => 'Classic Cotton T-Shirt',
                'slug' => 'cotton-tshirt',
                'description' => '100% organic cotton t-shirt with a comfortable fit. Available in multiple colors and sizes.',
                'price' => 29.99,
                'original_price' => 39.99,
                'category_id' => 2,
                'brand_id' => 2,
                'rating' => 4.50,
                'reviews_count' => 567,
                'stock' => 120,
                'in_stock' => true,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'sku' => 'HOME-001',
                'name' => 'Modern Desk Lamp',
                'slug' => 'modern-desk-lamp',
                'description' => 'Sleek LED desk lamp with adjustable brightness and color temperature. Perfect for any workspace.',
                'price' => 79.99,
                'original_price' => null,
                'category_id' => 3,
                'brand_id' => 3,
                'rating' => 4.60,
                'reviews_count' => 89,
                'stock' => 67,
                'in_stock' => true,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'sku' => 'SPORT-001',
                'name' => 'Yoga Mat Premium',
                'slug' => 'yoga-mat',
                'description' => 'Non-slip yoga mat made from eco-friendly materials. 6mm thickness for extra comfort.',
                'price' => 49.99,
                'original_price' => 69.99,
                'category_id' => 4,
                'brand_id' => 4,
                'rating' => 4.70,
                'reviews_count' => 145,
                'stock' => 89,
                'in_stock' => true,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'sku' => 'TECH-002',
                'name' => 'Smartphone Pro Max',
                'slug' => 'smartphone-pro',
                'description' => 'Latest flagship smartphone with advanced camera system, 5G connectivity, and all-day battery.',
                'price' => 999.99,
                'original_price' => 1199.99,
                'category_id' => 1,
                'brand_id' => 1,
                'rating' => 4.90,
                'reviews_count' => 1023,
                'stock' => 23,
                'in_stock' => true,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'sku' => 'FASH-002',
                'name' => 'Leather Crossbody Bag',
                'slug' => 'leather-bag',
                'description' => 'Genuine leather crossbody bag with multiple compartments. Perfect for everyday use.',
                'price' => 129.99,
                'original_price' => null,
                'category_id' => 2,
                'brand_id' => 2,
                'rating' => 4.40,
                'reviews_count' => 78,
                'stock' => 34,
                'in_stock' => true,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'sku' => 'HOME-002',
                'name' => 'Ceramic Coffee Mug Set',
                'slug' => 'coffee-mug-set',
                'description' => 'Set of 4 handcrafted ceramic mugs. Microwave and dishwasher safe.',
                'price' => 39.99,
                'original_price' => null,
                'category_id' => 3,
                'brand_id' => 3,
                'rating' => 4.50,
                'reviews_count' => 234,
                'stock' => 156,
                'in_stock' => true,
                'featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'sku' => 'SPORT-002',
                'name' => 'Running Shoes Pro',
                'slug' => 'running-shoes',
                'description' => 'Lightweight running shoes with advanced cushioning technology. Built for performance.',
                'price' => 159.99,
                'original_price' => 199.99,
                'category_id' => 4,
                'brand_id' => 4,
                'rating' => 4.80,
                'reviews_count' => 456,
                'stock' => 67,
                'in_stock' => true,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'sku' => 'FIT-002',
                'name' => 'Running Shoes Pro',
                'slug' => 'running-shoes-fitness',
                'description' => 'Lightweight running shoes with advanced cushioning technology. Built for performance.',
                'price' => 159.99,
                'original_price' => 199.99,
                'category_id' => 7,
                'brand_id' => 4,
                'rating' => 4.80,
                'reviews_count' => 456,
                'stock' => 50,
                'in_stock' => true,
                'featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
